# nvfetcher configuration for Nix flake inputs

[facter]
src.git = "https://github.com/nix-community/nixos-facter-modules"
fetch.github = "nix-community/nixos-facter-modules"

[nixos-hardware]
src.git = "https://github.com/NixOS/nixos-hardware"
fetch.github = "NixOS/nixos-hardware"

[disko]
src.git = "https://github.com/nix-community/disko"
fetch.github = "nix-community/disko"

[home]
src.git = "https://github.com/nix-community/home-manager"
fetch.github = "nix-community/home-manager"

[blog]
src.git = "https://tangled.org/@ptr.pet/endpoint"
fetch.git = "https://tangled.org/@ptr.pet/endpoint"

[agenix]
src.git = "https://github.com/ryantm/agenix"
fetch.github = "ryantm/agenix"

[ncr]
src.git = "https://tangled.org/@ptr.pet/nixos-cloud-resources"
fetch.git = "https://tangled.org/@ptr.pet/nixos-cloud-resources"

[limbusart]
src.git = "https://github.com/90-008/limbusart.git"
fetch.git = "https://github.com/90-008/limbusart.git"

[clickee]
src.git = "https://tangled.org/@ptr.pet/clickee"
fetch.git = "https://tangled.org/@ptr.pet/clickee"

[clickee-proxy]
src.git = "https://tangled.org/@ptr.pet/clickee-proxy"
fetch.git = "https://tangled.org/@ptr.pet/clickee-proxy"

[nsid-tracker]
src.git = "https://tangled.org/@ptr.pet/nsid-tracker"
fetch.git = "https://tangled.org/@ptr.pet/nsid-tracker"

[nucleus]
src.git = "https://tangled.org/@ptr.pet/nucleus"
fetch.git = "https://tangled.org/@ptr.pet/nucleus"

[trill]
src.git = "https://tangled.org/@ptr.pet/trill"
fetch.git = "https://tangled.org/@ptr.pet/trill"

[dysnomia]
src.git = "https://tangled.org/@ptr.pet/dysnomia"
fetch.git = "https://tangled.org/@ptr.pet/dysnomia"

[aturlist]
src.git = "https://tangled.org/@ptr.pet/aturlist"
fetch.git = "https://tangled.org/@ptr.pet/aturlist"

## TANGLED ##

[tangled]
src.git = "https://tangled.org/tangled.org/core"
fetch.git = "https://tangled.org/tangled.org/core"

[tangled-sqlite-lib]
src.manual = "3450100"
fetch.tarball = "https://sqlite.org/2024/sqlite-amalgamation-3450100.zip"

[gomod2nix]
src.git = "https://github.com/nix-community/gomod2nix"
fetch.github = "nix-community/gomod2nix"

## TANGLED ##

[moonlight]
src.git = "https://github.com/moonlight-mod/moonlight"
fetch.github = "moonlight-mod/moonlight"

[zen-browser]
src.git = "https://github.com/0xc000022070/zen-browser-flake"
fetch.github = "0xc000022070/zen-browser-flake"

[stylix]
src.git = "https://github.com/nix-community/stylix"
fetch.github = "nix-community/stylix"

[nixpkgs-xr]
src.git = "https://github.com/nix-community/nixpkgs-xr"
fetch.github = "nix-community/nixpkgs-xr"
