# nvfetcher configuration for Nix flake inputs

[headplane]
src.git = "https://github.com/90-008/headplane"
fetch.github = "90-008/headplane"

[lix-module]
src.manual = "2.93.2-1"
fetch.tarball = "https://git.lix.systems/lix-project/nixos-module/archive/2.93.2-1.tar.gz"

[nixos-wsl]
src.git = "https://github.com/nix-community/NixOS-WSL"
fetch.github = "nix-community/NixOS-WSL"

[home]
src.git = "https://github.com/nix-community/home-manager"
fetch.github = "nix-community/home-manager"

[blog]
src.git = "https://git.gaze.systems/90008/website.git"
fetch.git = "https://git.gaze.systems/90008/website.git"

[agenix]
src.git = "https://github.com/ryantm/agenix"
fetch.github = "ryantm/agenix"

[ncr]
src.git = "https://tangled.sh/@poor.dog/nixos-cloud-resources"
fetch.git = "https://tangled.sh/@poor.dog/nixos-cloud-resources"

[limbusart]
src.git = "https://git.gaze.systems/90008/limbusart.git"
fetch.git = "https://git.gaze.systems/90008/limbusart.git"

[nsid-tracker]
src.git = "https://tangled.sh/@poor.dog/nsid-tracker"
fetch.git = "https://tangled.sh/@poor.dog/nsid-tracker"

[tangled]
src.git = "https://tangled.sh/@poor.dog/core"
fetch.git = "https://tangled.sh/@poor.dog/core"

[tangled-sqlite-lib]
src.manual = "3450100"
fetch.tarball = "https://sqlite.org/2024/sqlite-amalgamation-3450100.zip"

[gomod2nix]
src.git = "https://github.com/nix-community/gomod2nix"
fetch.github = "nix-community/gomod2nix"
