name: deploy to server

on:
  push:
    tags:
      - 'latest'
  workflow_dispatch:

jobs:
  tag:
    runs-on: lixpine
    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: 'https://git.gaze.systems'
      - uses: https://github.com/cachix/cachix-action@v16
        with:
          name: gazesys-infra
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#nixosConfigurations.wolumonde.config.system.build.toplevel -L --show-trace