name: deploy to server

on:
  push:
  workflow_dispatch:

jobs:
  tag:
    runs-on: lixpine
    steps:
      - name: trigger deploy
        env:
          WEBHOOK_PASSWORD: ${{ secrets.WEBHOOK_PASSWORD }}
        run: curl -u "meow:$WEBHOOK_PASSWORD" https://webhook.gaze.systems/deploy-wolumonde