# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  agenix = {
    pname = "agenix";
    version = "531beac616433bac6f9e2a19feb8e99a22a66baf";
    src = fetchFromGitHub {
      owner = "ryantm";
      repo = "agenix";
      rev = "531beac616433bac6f9e2a19feb8e99a22a66baf";
      fetchSubmodules = false;
      sha256 = "sha256-9P1FziAwl5+3edkfFcr5HeGtQUtrSdk/MksX39GieoA=";
    };
    date = "2025-06-17";
  };
  blog = {
    pname = "blog";
    version = "420c26e68b1aebe29a880be60ead8b00954c9ace";
    src = fetchgit {
      url = "https://git.gaze.systems/90008/website.git";
      rev = "420c26e68b1aebe29a880be60ead8b00954c9ace";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MxamnEYU/CeMq98GNzliN+vwBYE9+Jq8FUD2cRH0x7U=";
    };
    date = "2025-07-22";
  };
  gomod2nix = {
    pname = "gomod2nix";
    version = "be828766411cad04c194c8f714d46aa2b2596362";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "gomod2nix";
      rev = "be828766411cad04c194c8f714d46aa2b2596362";
      fetchSubmodules = false;
      sha256 = "sha256-MaaWYgN/nia7xJcOYLBtPk+cFo7X2zEM1d9xIGPQrLU=";
    };
    date = "2025-07-21";
  };
  headplane = {
    pname = "headplane";
    version = "e9fe8625db3b03c121e0b7fb50add4cd729d986c";
    src = fetchFromGitHub {
      owner = "90-008";
      repo = "headplane";
      rev = "e9fe8625db3b03c121e0b7fb50add4cd729d986c";
      fetchSubmodules = false;
      sha256 = "sha256-KM7Jxrab3o38tJr3gA6wQ2zalZ2N5yK4d65r3KhGZKg=";
    };
    date = "2025-07-23";
  };
  home = {
    pname = "home";
    version = "0cdfcdbb525b77b951c889b6131047bc374f48fe";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "0cdfcdbb525b77b951c889b6131047bc374f48fe";
      fetchSubmodules = false;
      sha256 = "sha256-CLQfNtUqirNVSYoW/kYbvL4PeeNasmZonaPnjO3+1YQ=";
    };
    date = "2025-07-22";
  };
  limbusart = {
    pname = "limbusart";
    version = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
    src = fetchgit {
      url = "https://git.gaze.systems/90008/limbusart.git";
      rev = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xATZz/sHYHkEXjwcmq1DSntclWxnDIKCpH314MaL63U=";
    };
    date = "2025-07-22";
  };
  lix-module = {
    pname = "lix-module";
    version = "2.93.2-1";
    src = fetchTarball {
      url = "https://git.lix.systems/lix-project/nixos-module/archive/2.93.2-1.tar.gz";
      sha256 = "sha256-SXUAlxpjPRkArRMHy5+Hdi+PiC+ND9yzzIjiaHmTvQU=";
    };
  };
  ncr = {
    pname = "ncr";
    version = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
    src = fetchgit {
      url = "https://tangled.sh/@poor.dog/nixos-cloud-resources";
      rev = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-miZ64o8p+ToR6VIpcco/wq0rdHGjHsfepJdMcSiJEDk=";
    };
    date = "2025-07-18";
  };
  nixos-wsl = {
    pname = "nixos-wsl";
    version = "20001f9bf0aaf2b1c307e43a5eec8cf8f800fe14";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "NixOS-WSL";
      rev = "20001f9bf0aaf2b1c307e43a5eec8cf8f800fe14";
      fetchSubmodules = false;
      sha256 = "sha256-ZNIpqCG/CfhmV+TgIeyO/XbhDjSWpwWokHM44j0Mn0w=";
    };
    date = "2025-07-16";
  };
  nsid-tracker = {
    pname = "nsid-tracker";
    version = "c806b451e23d06340e5acc0c355711b0b9eddc64";
    src = fetchgit {
      url = "https://tangled.sh/@poor.dog/nsid-tracker";
      rev = "c806b451e23d06340e5acc0c355711b0b9eddc64";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yPANagtG948e5N8OQrG78w+jUSH4/PFUSILKgTc1i6E=";
    };
    date = "2025-07-26";
  };
  tangled = {
    pname = "tangled";
    version = "a2586d477f5908cabea2d04a9a50557e52bcf416";
    src = fetchgit {
      url = "https://tangled.sh/@tangled.sh/core";
      rev = "a2586d477f5908cabea2d04a9a50557e52bcf416";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vQuHKJumfkS8S3vJkBaGzbSsJQT9ntmdW6IdZs2YXtY=";
    };
    date = "2025-07-25";
  };
  tangled-sqlite-lib = {
    pname = "tangled-sqlite-lib";
    version = "3450100";
    src = fetchTarball {
      url = "https://sqlite.org/2024/sqlite-amalgamation-3450100.zip";
      sha256 = "sha256-bJoMjirsBjm2Qk9KPiy3yV3+8b/POlYe76/FQbciHro=";
    };
  };
}
