# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  agenix = {
    pname = "agenix";
    version = "9edb1787864c4f59ae5074ad498b6272b3ec308d";
    src = fetchFromGitHub {
      owner = "ryantm";
      repo = "agenix";
      rev = "9edb1787864c4f59ae5074ad498b6272b3ec308d";
      fetchSubmodules = false;
      sha256 = "sha256-NA/FT2hVhKDftbHSwVnoRTFhes62+7dxZbxj5Gxvghs=";
    };
    date = "2025-08-05";
  };
  blog = {
    pname = "blog";
    version = "fdee952ff5d9829e08b47fa7438b3b64b1212fa5";
    src = fetchgit {
      url = "https://git.gaze.systems/90008/website.git";
      rev = "fdee952ff5d9829e08b47fa7438b3b64b1212fa5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8dhgQTSwDfUrnsUzwlwmM7KK0FvoFZUllNFM3LWUqx8=";
    };
    date = "2025-09-03";
  };
  gomod2nix = {
    pname = "gomod2nix";
    version = "47d628dc3b506bd28632e47280c6b89d3496909d";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "gomod2nix";
      rev = "47d628dc3b506bd28632e47280c6b89d3496909d";
      fetchSubmodules = false;
      sha256 = "sha256-JeuGh9kA1SPL70fnvpLxkIkCWpTjtoPaus3jzvdna0k=";
    };
    date = "2025-08-24";
  };
  home = {
    pname = "home";
    version = "f3d3b4592a73fb64b5423234c01985ea73976596";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "f3d3b4592a73fb64b5423234c01985ea73976596";
      fetchSubmodules = false;
      sha256 = "sha256-LOrOfPWpJU/ADWDyVwPv9XNuYPq5KJtmAmSzplpccmE=";
    };
    date = "2025-09-01";
  };
  limbusart = {
    pname = "limbusart";
    version = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
    src = fetchgit {
      url = "https://git.gaze.systems/90008/limbusart.git";
      rev = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xATZz/sHYHkEXjwcmq1DSntclWxnDIKCpH314MaL63U=";
    };
    date = "2025-07-22";
  };
  lix-module = {
    pname = "lix-module";
    version = "2.93.3-1";
    src = fetchTarball {
      url = "https://git.lix.systems/lix-project/nixos-module/archive/2.93.3-1.tar.gz";
      sha256 = "sha256-KYMUrTV7H/RR5/HRnjV5R3rRIuBXMemyJzTLi50NFTs=";
    };
  };
  ncr = {
    pname = "ncr";
    version = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
    src = fetchgit {
      url = "https://tangled.sh/@poor.dog/nixos-cloud-resources";
      rev = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-miZ64o8p+ToR6VIpcco/wq0rdHGjHsfepJdMcSiJEDk=";
    };
    date = "2025-07-18";
  };
  nixos-wsl = {
    pname = "nixos-wsl";
    version = "203a7b463f307c60026136dd1191d9001c43457f";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "NixOS-WSL";
      rev = "203a7b463f307c60026136dd1191d9001c43457f";
      fetchSubmodules = false;
      sha256 = "sha256-EOqCupB5X5WoGVHVcfOZcqy0SbKWNuY3kq+lj1wHdu8=";
    };
    date = "2025-08-15";
  };
  nsid-tracker = {
    pname = "nsid-tracker";
    version = "b7d77d2231d05303be46a9610f5a7351264c0e00";
    src = fetchgit {
      url = "https://tangled.sh/@poor.dog/nsid-tracker";
      rev = "b7d77d2231d05303be46a9610f5a7351264c0e00";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nt204Rhdo/JRgZs5SecifTtyUUszY6rWfMhh7ac8Loc=";
    };
    date = "2025-08-23";
  };
  tangled = {
    pname = "tangled";
    version = "da3540c0c134331c10f1a8d124ee0925e57f8112";
    src = fetchgit {
      url = "https://tangled.sh/@tangled.sh/core";
      rev = "da3540c0c134331c10f1a8d124ee0925e57f8112";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yD8PMlRjUI2sN5PvkDJRfGz96zCp4gejaguDVmZ4utg=";
    };
    date = "2025-09-01";
  };
  tangled-sqlite-lib = {
    pname = "tangled-sqlite-lib";
    version = "3450100";
    src = fetchTarball {
      url = "https://sqlite.org/2024/sqlite-amalgamation-3450100.zip";
      sha256 = "sha256-bJoMjirsBjm2Qk9KPiy3yV3+8b/POlYe76/FQbciHro=";
    };
  };
}
