# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  agenix = {
    pname = "agenix";
    version = "fcdea223397448d35d9b31f798479227e80183f6";
    src = fetchFromGitHub {
      owner = "ryantm";
      repo = "agenix";
      rev = "fcdea223397448d35d9b31f798479227e80183f6";
      fetchSubmodules = false;
      sha256 = "sha256-wyT7Pl6tMFbFrs8Lk/TlEs81N6L+VSybPfiIgzU8lbQ=";
    };
    date = "2025-11-08";
  };
  blog = {
    pname = "blog";
    version = "00bc18c0a7c74fcf3a8f0ede70e5ee3f3f7d7797";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/endpoint";
      rev = "00bc18c0a7c74fcf3a8f0ede70e5ee3f3f7d7797";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4TbxOa4V13/WspjKyfKDguKoIDVKRogOa+Rl0bSg2/U=";
    };
    date = "2025-12-01";
  };
  clickee-proxy = {
    pname = "clickee-proxy";
    version = "a60247a8d92e1802298fc197034d0b7b54cd90b7";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/clickee-proxy";
      rev = "a60247a8d92e1802298fc197034d0b7b54cd90b7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sMLvbvnhGGt+LpKmD3e/iPcEtUd6Yu+92DTlEwHxZCI=";
    };
    date = "2025-09-15";
  };
  disko = {
    pname = "disko";
    version = "aecba248f9a7d68c5d1ed15de2d1c8a4c994a3c5";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "disko";
      rev = "aecba248f9a7d68c5d1ed15de2d1c8a4c994a3c5";
      fetchSubmodules = false;
      sha256 = "sha256-xanUzIb0tf3kJ+PoOFmXEXV1jM3PjkDT/TQ5DYeNYRc=";
    };
    date = "2025-11-25";
  };
  facter = {
    pname = "facter";
    version = "fa695bff9ec37fd5bbd7ee3181dbeb5f97f53c96";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nixos-facter-modules";
      rev = "fa695bff9ec37fd5bbd7ee3181dbeb5f97f53c96";
      fetchSubmodules = false;
      sha256 = "sha256-iaRf6n0KPl9hndnIft3blm1YTAyxSREV1oX0MFZ6Tk4=";
    };
    date = "2025-11-04";
  };
  gomod2nix = {
    pname = "gomod2nix";
    version = "02e63a239d6eabd595db56852535992c898eba72";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "gomod2nix";
      rev = "02e63a239d6eabd595db56852535992c898eba72";
      fetchSubmodules = false;
      sha256 = "sha256-ur4QIAHwgFc0vXiaxn5No/FuZicxBr2p0gmT54xZkUQ=";
    };
    date = "2025-11-24";
  };
  home = {
    pname = "home";
    version = "9651819d75f6c7ffaf8a9227490ac704f29659f0";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "9651819d75f6c7ffaf8a9227490ac704f29659f0";
      fetchSubmodules = false;
      sha256 = "sha256-iUM9ktarEzThkayyZrzQ7oycPshAY2XRQqVKz0xX/L0=";
    };
    date = "2025-11-26";
  };
  limbusart = {
    pname = "limbusart";
    version = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
    src = fetchgit {
      url = "https://git.gaze.systems/90008/limbusart.git";
      rev = "7f29ab57b73eb8a4db7163fc7d19a71cf89c3d8b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xATZz/sHYHkEXjwcmq1DSntclWxnDIKCpH314MaL63U=";
    };
    date = "2025-07-22";
  };
  moonlight = {
    pname = "moonlight";
    version = "059476af87f7335c05424b805833864d6d9ed0e3";
    src = fetchFromGitHub {
      owner = "moonlight-mod";
      repo = "moonlight";
      rev = "059476af87f7335c05424b805833864d6d9ed0e3";
      fetchSubmodules = false;
      sha256 = "sha256-Qur5AWl4Vx+It65DX+I+sc4lViz52OmXqvg+fL2t9I4=";
    };
    date = "2025-11-26";
  };
  ncr = {
    pname = "ncr";
    version = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/nixos-cloud-resources";
      rev = "4660aa9cd9b24bef569696eee46dbe7e8df3e237";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-miZ64o8p+ToR6VIpcco/wq0rdHGjHsfepJdMcSiJEDk=";
    };
    date = "2025-07-18";
  };
  nixos-hardware = {
    pname = "nixos-hardware";
    version = "da17006633ca9cda369be82893ae36824a2ddf1a";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixos-hardware";
      rev = "da17006633ca9cda369be82893ae36824a2ddf1a";
      fetchSubmodules = false;
      sha256 = "sha256-b1MtLQsQc4Ji1u08f+C6g5XrmLPkJQ1fhNkCt+0AERQ=";
    };
    date = "2025-11-25";
  };
  nixpkgs-xr = {
    pname = "nixpkgs-xr";
    version = "cd67b4986ffb7c4b136b6d4286c94375c74867bc";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nixpkgs-xr";
      rev = "cd67b4986ffb7c4b136b6d4286c94375c74867bc";
      fetchSubmodules = false;
      sha256 = "sha256-D8d1g9aaZlTc/xZjbeaHJUwmJDAOqjqZNucMrq6wCKc=";
    };
    date = "2025-11-27";
  };
  nsid-tracker = {
    pname = "nsid-tracker";
    version = "2683e619932808b8aa78ec7100de6324c8216daf";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/nsid-tracker";
      rev = "2683e619932808b8aa78ec7100de6324c8216daf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-utNIYZiuPql6gvM8k8T/NuLomFRWknfbFvvHpXPei3k=";
    };
    date = "2025-09-11";
  };
  nucleus = {
    pname = "nucleus";
    version = "a4f73517c1a76ed20b55f21618148b8afe0fa838";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/nucleus";
      rev = "a4f73517c1a76ed20b55f21618148b8afe0fa838";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8WrGAr+aCIFCFuixtH1BSB5lMn+d/FqXsEFAmXY3HkU=";
    };
    date = "2025-11-11";
  };
  stylix = {
    pname = "stylix";
    version = "70c444a10d0c9ef71a25580dfa79af9cd43f3a5e";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "stylix";
      rev = "70c444a10d0c9ef71a25580dfa79af9cd43f3a5e";
      fetchSubmodules = false;
      sha256 = "sha256-rofXPD/9TGpHveo1MTlUfpnF0MCG1/uHUB9f0rosdqc=";
    };
    date = "2025-11-26";
  };
  tangled = {
    pname = "tangled";
    version = "7358ec6edfa4d17b8b8f543d99e83a4705901148";
    src = fetchgit {
      url = "https://tangled.org/@tangled.org/core";
      rev = "7358ec6edfa4d17b8b8f543d99e83a4705901148";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PzuWiW/nMxwQTX0i1bHwGazQF4ptLNI9OGwpmhDb9i0=";
    };
    date = "2025-11-24";
  };
  tangled-sqlite-lib = {
    pname = "tangled-sqlite-lib";
    version = "3450100";
    src = fetchTarball {
      url = "https://sqlite.org/2024/sqlite-amalgamation-3450100.zip";
      sha256 = "sha256-bJoMjirsBjm2Qk9KPiy3yV3+8b/POlYe76/FQbciHro=";
    };
  };
  trill = {
    pname = "trill";
    version = "c9604685156e009cebd0ddc3b31672455f635387";
    src = fetchgit {
      url = "https://tangled.org/@ptr.pet/trill";
      rev = "c9604685156e009cebd0ddc3b31672455f635387";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-so9EHN0GQ7rFSmnLnpRap2RqRcklhe3C1HdyAKeR6No=";
    };
    date = "2025-11-25";
  };
  zen-browser = {
    pname = "zen-browser";
    version = "6f5d615393a5e923ea2883ef28e274031d1b1e1e";
    src = fetchFromGitHub {
      owner = "0xc000022070";
      repo = "zen-browser-flake";
      rev = "6f5d615393a5e923ea2883ef28e274031d1b1e1e";
      fetchSubmodules = false;
      sha256 = "sha256-AEpt8JdKA4RVobRjaR7S2QP3bmUz8dhuWasB7mr9Ylo=";
    };
    date = "2025-11-26";
  };
}
