# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "sr_mod"
    "xen_blkfront"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  networking.useDHCP = false;

  systemd.network.enable = true;
  systemd.network.wait-online.enable = false;
  systemd.network.networks."enX0" = {
    matchConfig = {
      Name = "enX0";
    };
    address = [ "199.71.188.53/29" ];
    gateway = [ "199.71.188.49" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
